on:
  push:
    branches:
      - "main"
name: Build and Deploy to GH Pages
jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: build
        run: |
          mkdir bin
          wget https://github.com/getzola/zola/releases/download/v0.21.0/zola-v0.21.0-x86_64-unknown-linux-gnu.tar.gz -q -O bin/zola.tar.gz
          tar -xzf ./bin/zola.tar.gz -C ./bin
          chmod +x ./bin/zola
          ./bin/zola build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build
    name: Deploy to GH Pages
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy Site
        id: deployment
        uses: actions/deploy-pages@v4
